BusManagement/force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

BusManagement/force-app/main/default/objects/Bus__c/fields/Passenger_Count__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Count__c</fullName>
    <label>Passenger Count</label>
    <summaryForeignKey>Bus_Assignment__c.Bus__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

BusManagement/force-app/main/default/classes/BusUpdateStatusRepository.cls
/**
 * Created by RokasL on 5/31/2025.
 */

public with sharing class BusUpdateStatusRepository
{
    public List<Bus__c> getBusesByIds(List<Id> busIds)
    {
        return [
            SELECT
                Id,
                Bus_Status__c,
                Passenger_Count__c
            FROM
                Bus__c
            WHERE
                Id IN :busIds
        ];
    }

    public void updateBuses(List<Bus__c> busList)
    {
        update busList;
    }
}